### ISSUE TITLE
创建CPU分区作业，选择1个节点，单节点CPU核心为奇数时，自动修改为偶数

### ISSUE THREAD

**Issue by zhengkang2020** [PKUHPC/OpenSCOW#1000]
创建CPU分区作业，选择1个节点，单节点CPU核心为1时，自动修改为2
![image](https://github.com/PKUHPC/SCOW/assets/67989011/8d9dfa27-6c81-4952-930a-80fdf4bf1a34)

![image](https://github.com/PKUHPC/SCOW/assets/67989011/1b84d2b5-cbf5-45fa-8cb4-8f11ebaad65c)

**Comment by lingbozeng** [comment]
您这个问题有确切的复现方法没？

**Comment by zhengkang2020** [comment]
不确定是什么问题，不清楚怎么复现。
现在我只要创建1节点1核心的应用，查看就是2核心的

**Comment by zhengkang2020** [comment]
@lingbozeng 在哪里能看到新建作业的日志？是portal-server还是什么？

**Comment by vanstriker** [comment]
请在新版确认是否能复现该问题

**Comment by zhengkang2020** [comment]
我这里有2个相同的环境，一个开发环境，一个虚拟测试环境，都是1.5版本，配置文件基本相同。
开发环境有这个问题，测试环境没有这个问题，哪里能对这个问题进行排错呢？

**Comment by vanstriker** [comment]
1、检查slurm是否有相关配置
2、检查portal-server提交到适配器的请求参数是什么
3、看看demo集群是否能复现

**Comment by zhengkang2020** [comment]
1. slurm用的配置文件除节点信息以外都是一样的
2. portal-server提交到适配器的请求参数怎么查看？
3. demo集群不能复现

**Comment by vanstriker** [comment]
已解决

**Comment by zhengkang2020** [comment]
#1000 与#1445 是2个问题，#1445 解决了，#1000 还是会有这个问题。
