### ISSUE TITLE
文件管理中的软连接会被识别为一个文件

### ISSUE THREAD

**Issue by zhengkang2020** [PKUHPC/OpenSCOW#1228]
### 发生了什么 | What happened

在用户目录中新建软连接，`ln -s /data/home/test/test11 /data/home/test111` ，文件管理中会被识别为一个文件，但是在shell中是能正常使用的。
![image](https://github.com/PKUHPC/SCOW/assets/67989011/cacae921-d970-4f59-a3fd-b2047abbc4d8)

**Comment by vanstriker** [comment]
已经复现，后续我们会安排处理

**Comment by vanstriker** [comment]
后续在 #1452 中跟进该issue内容
