### ISSUE TITLE
新建账户欠费封锁无效

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/OpenSCOW#1371]
### 发生了什么 | What happened

新建两个帐户，一个账户有充值，一个账户没有充值，充值账户提交作业到欠费状态后，点过"账户封锁状态同步"，两个账户还可以提交作业。
<img width="855" alt="image" src="https://github.com/user-attachments/assets/0a20d294-b47e-4ecf-8379-93a4c1f36429">

### 运行环境 | Environment

```Markdown
- OS: ubuntu 20.04
- Scheduler: 23.11.0
- Docker: 24.0.9
- Docker-compose: v2.24.1
- SCOW cli: 1.5.2
- SCOW: 1.5.2
- Adapter: 1.5
```

**Comment by vanstriker** [comment]
欠费状态是可以用的，看看是否在白名单里面

**Comment by liu-shaobo** [comment]
在1.6.2版本下新建1个帐户，账户没有充值，可以提交作业。
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/46142b44-00eb-4a47-8d28-264761f7be84">


### 运行环境 | Environment

```Markdown
- OS: ubuntu 20.04
- Scheduler: 23.11.0
- Docker: 24.0.9
- Docker-compose: v2.24.1
- SCOW cli: 1.6.2
- SCOW: 1.6.2
- Adapter: 1.6.0
```

**Comment by vanstriker** [comment]
请确认adapter的封锁操作是有效的

**Comment by liu-shaobo** [comment]
测试下来，应当是不支持slurm 23.x.x版本。

**Comment by tongchong** [comment]
因此issue问题在于slurm 23.x.x版本执行命令失败，不是scow的原因，此问题暂时关闭
