### ISSUE TITLE
[Bug/Help] auth: Error response from daemon: pull access denied for mirrors.pku.edu.cn/pkuhpc-icode/scow

### ISSUE THREAD

**Issue by qq572841383** [PKUHPC/OpenSCOW#1405]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 发生了什么 | What happened

Error response from daemon: pull access denied for mirrors.pku.edu.cn/pkuhpc-icode/scow, repository does not exist or may require 'docker login': denied: <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>

### 复现方法 | Steps To Reproduce

./cli compose up -d

### 运行环境 | Environment

```Markdown
- OS:
- Scheduler:
- Docker:
- Docker-compose:
- SCOW cli:
- SCOW:
- Adapter:
```

**Comment by fuzhenxin** [comment]
请提供一下具体的时间，以方便我们查看日志。请同一时间curl https://mirrors.pku.edu.cn/xxxxxxxxxxxxx  我们看一下源IP。

**Comment by qq572841383** [comment]
> 请提供一下具体的时间，以方便我们查看日志。请同一时间curl https://mirrors.pku.edu.cn/xxxxxxxxxxxxx 我们看一下源IP。

目前可以通过./cli compose up -d拉下来了，但是容器scow-mis-server-1异常：
# docker logs scow-mis-server-1

> @scow/mis-server@1.6.3 serve
> node build/index.js

{"level":30,"time":"2024-08-28T08:34:26.854Z","pid":18,"hostname":"2d79bc38bd50","msg":"Hook is not configured."}
{"level":30,"time":"2024-08-28T08:34:27.016Z","pid":18,"hostname":"2d79bc38bd50","version":{"commit":"92dd66681c6585ba41228439560b283a2a95b60b"},"msg":"@scow/mis-server: "}
{"level":30,"time":"2024-08-28T08:34:27.016Z","pid":18,"hostname":"2d79bc38bd50","config":{"HOST":"0.0.0.0","PORT":5000,"LOG_LEVEL":"info","LOG_PRETTY":false,"SSH_PRIVATE_KEY_PATH":"/root/.ssh/id_rsa","SSH_PUBLIC_KEY_PATH":"/root/.ssh/id_rsa.pub","AUTH_URL":"","DB_PASSWORD":"must!chang3this"},"msg":"Loaded env config"}
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: connect ECONNREFUSED 172.22.0.3:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.22.0.3',
  port: 3306,
  fatal: true
}

Node.js v20.17.0

> @scow/mis-server@1.6.3 serve
> node build/index.js


以及：
# docker ps
CONTAINER ID   IMAGE                                         COMMAND                   CREATED          STATUS                          PORTS                                                                                                    NAMES
9b3d2ed02b96   mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"         16 minutes ago   Up 16 minutes                   3000/tcp, 0.0.0.0:80->80/tcp, :::80->80/tcp, 5000/tcp                                                    scow-gateway-1
508f447baae0   mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"         16 minutes ago   Restarting (1) 20 seconds ago                                                                                                            scow-portal-server-1
99e5f3df2e3f   redis:alpine                                  "docker-entrypoint.s…"   16 minutes ago   Up 16 minutes                   6379/tcp                                                                                                 scow-redis-1
f038d52d3370   ghcr.io/pkuhpc/novnc-client-docker:master     "/docker-entrypoint.…"   16 minutes ago   Up 16 minutes                   80/tcp                                                                                                   scow-novnc-1
2d79bc38bd50   mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"         16 minutes ago   Up About a minute               80/tcp, 3000/tcp, 5000/tcp                                                                               scow-mis-server-1
e9f8c9650c23   mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"         16 minutes ago   Up 16 minutes                   80/tcp, 3000/tcp, 5000/tcp                                                                               scow-portal-web-1
c33d87c5f8f8   mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"         16 minutes ago   Up 16 minutes                   80/tcp, 3000/tcp, 5000/tcp                                                                               scow-mis-web-1
7fba2a861808   mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"         16 minutes ago   Up 16 minutes                   80/tcp, 3000/tcp, 5000/tcp                                                                               scow-audit-server-1
f939fa572141   mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"         16 minutes ago   Up 16 minutes                   80/tcp, 3000/tcp, 5000/tcp                                                                               scow-auth-1
174eddae16cf   mysql:8                                       "docker-entrypoint.s…"   16 minutes ago   Up 16 minutes                   3306/tcp, 33060/tcp                                                                                      scow-db-1
633d3d7d20e7   mysql:8                                       "docker-entrypoint.s…"   16 minutes ago   Up 16 minutes                   3306/tcp, 33060/tcp                                                                                      scow-audit-db-1
663ac03e552c   fluentd:v1.14.0-1.0                           "tini -- /bin/entryp…"   16 minutes ago   Up 16 minutes                   5140/tcp, 0.0.0.0:24224->24224/tcp, 0.0.0.0:24224->24224/udp, :::24224->24224/tcp, :::24224->24224/udp   scow-log-1

**Comment by Miracle575** [comment]
根据日志判断，时 mis-server 容器未连接上数据库，请检查数据库连接配置（密码，地址等）是否正确。或提供一份您的配置

**Comment by vanstriker** [comment]
无更新回复，关闭issue
