### ISSUE TITLE
用户空间“未结束的作业”不显示

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/OpenSCOW#1407]
用户空间的未结束作业不显示

* 用户空间
<img width="1210" alt="image" src="https://github.com/user-attachments/assets/964e9243-8053-4884-93fd-b4373085d7f2">

* 租户管理
<img width="1178" alt="image" src="https://github.com/user-attachments/assets/6c927ddb-63c4-42e2-9c99-ead3fc74801e">

### 运行环境 | Environment
```Markdown
- OS: ubuntu 20.04
- Scheduler: 23.11.0
- Docker: 24.0.9
- Docker-compose: v2.24.1
- SCOW cli: 1.6.2
- SCOW: master
- Adapter: 1.6
```

**Comment by tongchong** [comment]
您使用的scow是最新版本吗？我没有在1.6.3版本复现该问题

**Comment by liu-shaobo** [comment]
今天全新安装了下1.6.3没有发现这个问题
