### ISSUE TITLE
[Feature/Enhancement] portal: 当分区为Hidden时，该分区不应显示在仪表盘页面中

### ISSUE THREAD

**Issue by wyzhh** [PKUHPC/OpenSCOW#1441]
### 为何需要此功能 | Why is this needed

当分区配置为Slurm的Hidden分区时，仪表盘不应再展示该分区。

### 希望增加什么 | What would you like to be added

当分区配置为Slurm的Hidden分区时，仪表盘不应再展示该分区。

### 此功能为谁设计？ | Who is this feature for?

普通用户

**Comment by tongchong** [comment]
这需要修改适配器的代码，可以选择不返回hidden分区，或在状态中增加hidden标识，然后让scow去判断，倾向于直接修改适配器的代码

**Comment by wyzhh** [comment]
> 这需要修改适配器的代码，可以选择不返回hidden分区，或在状态中增加hidden标识，然后让scow去判断，倾向于直接修改适配器的代码

感谢回复，如果不返回hidden分区的话，该分区下的用户还能在网页中选到该分区吗？

**Comment by vanstriker** [comment]
无更新回复，关闭issue
